CREATE TABLE [dbo].[users] (
    [Id]       INT           IDENTITY (1, 1) NOT NULL,
	[FIRSTNAME] NVARCHAR(40) NOT NULL,
	[LASTNAME] NVARCHAR(40) NOT NULL,
    [USERNAME] NVARCHAR (40) NOT NULL,
    [PASSWORD] NVARCHAR (40) NOT NULL,
	[EMAIL] NVARCHAR (40) NOT NULL,
	[PHONENUMBER] NVARCHAR(40) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

